### ISSUE TITLE
Calls not receiving in iOS 16

### ISSUE THREAD

**Issue by peddireddykishore** [KaleyraVideo/VideoiOSSDK#1]
We have tested my app in iOS 14 and iOS 15 versions calls are being received for the user. But when we try same user in iOS 16, we are not able receive calls or chats. 

We are using Bandyer 2.9.0 version in iOS.

Edit 1 : We observed  the below callClient Observer function is not being called when there is a new incoming call in iOS 16.
- (void)callClient:(id <BDKCallClient>)client didReceiveIncomingCall:(id <BDKCall>)call;

**Comment by peddireddykishore** [comment]
Response: outputDeviceVolume<9C584A11-BCED-4BF0-A63C-2974ADD9DF21> returned with error <Error Domain=kMRMediaRemoteFrameworkErrorDomain Code=36 "Endpoint volume control is only possible if the endpoint is picked or remote controllable." UserInfo={NSLocalizedDescription=Endpoint volume control is only possible if the endpoint is picked or remote controllable.}> for <MRAVLocalEndpoint:0x283c67880>:LOCAL-System Capture-(null) in 0.0009 seconds

Above are the logs while attempting to make out going call.

**Comment by MarcoBrescianini** [comment]
Actually there isn't such issue. The problem was the device receiving the incoming call had the "do not disturb" mode enabled
